// <auto-generated />
using System;
using HendrixRFID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HendrixRFID.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504103954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HendrixRFID.Models.Lamp", b =>
                {
                    b.Property<string>("LampId")
                        .HasColumnType("TEXT");

                    b.HasKey("LampId");

                    b.ToTable("Lamps");
                });

            modelBuilder.Entity("HendrixRFID.Models.Pig", b =>
                {
                    b.Property<string>("PigId")
                        .HasColumnType("TEXT");

                    b.HasKey("PigId");

                    b.ToTable("Pigs");
                });

            modelBuilder.Entity("HendrixRFID.Models.RawScan", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScanId");

                    b.ToTable("RawScans");
                });
#pragma warning restore 612, 618
        }
    }
}
