// <auto-generated />
using System;
using HendrixRFID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HendrixRFID.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HendrixRFID.Models.Lamp", b =>
                {
                    b.Property<string>("LampId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacedIn")
                        .HasColumnType("INTEGER");

                    b.HasKey("LampId");

                    b.HasIndex("PlacedIn");

                    b.ToTable("Lamps");
                });

            modelBuilder.Entity("HendrixRFID.Models.Pig", b =>
                {
                    b.Property<string>("PigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BelongsTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("PigId");

                    b.HasIndex("BelongsTo");

                    b.ToTable("Pigs");
                });

            modelBuilder.Entity("HendrixRFID.Models.PigHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromLampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HistoryId");

                    b.HasIndex("LampId");

                    b.HasIndex("PigId");

                    b.ToTable("PigHistories");
                });

            modelBuilder.Entity("HendrixRFID.Models.PigLocation", b =>
                {
                    b.Property<string>("PigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentLampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("PigId");

                    b.HasIndex("CurrentLampId");

                    b.ToTable("PigLocations");
                });

            modelBuilder.Entity("HendrixRFID.Models.RawScan", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScanId");

                    b.HasIndex("LampId");

                    b.HasIndex("PigId");

                    b.ToTable("RawScans");
                });

            modelBuilder.Entity("HendrixRFID.Models.Stable", b =>
                {
                    b.Property<int>("StableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("StableId");

                    b.ToTable("Stables");
                });

            modelBuilder.Entity("HendrixRFID.Models.Lamp", b =>
                {
                    b.HasOne("HendrixRFID.Models.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("PlacedIn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("HendrixRFID.Models.Pig", b =>
                {
                    b.HasOne("HendrixRFID.Models.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("BelongsTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("HendrixRFID.Models.PigHistory", b =>
                {
                    b.HasOne("HendrixRFID.Models.Lamp", "Lamp")
                        .WithMany()
                        .HasForeignKey("LampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HendrixRFID.Models.Pig", "Pig")
                        .WithMany()
                        .HasForeignKey("PigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lamp");

                    b.Navigation("Pig");
                });

            modelBuilder.Entity("HendrixRFID.Models.PigLocation", b =>
                {
                    b.HasOne("HendrixRFID.Models.Lamp", "Lamp")
                        .WithMany()
                        .HasForeignKey("CurrentLampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HendrixRFID.Models.Pig", "Pig")
                        .WithOne()
                        .HasForeignKey("HendrixRFID.Models.PigLocation", "PigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lamp");

                    b.Navigation("Pig");
                });

            modelBuilder.Entity("HendrixRFID.Models.RawScan", b =>
                {
                    b.HasOne("HendrixRFID.Models.Lamp", "Lamp")
                        .WithMany()
                        .HasForeignKey("LampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HendrixRFID.Models.Pig", "Pig")
                        .WithMany()
                        .HasForeignKey("PigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lamp");

                    b.Navigation("Pig");
                });
#pragma warning restore 612, 618
        }
    }
}
